blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('category/<slug:slug>/', views.category_view, name='category'),
    path('tag/<slug:slug>/', views.tag_view, name='tag'),
]

main/urls.py
from django.urls import path
from .views import *
from main.views import robots_txt
from . import views 

urlpatterns = [
    path('', home, name='home'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('chat/opciones/', opciones, name='opciones'),
    path('cookie-policy/', views.cookie_policy, name='cookie_policy'),
    path('terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('chat/webchat/', webchat, name='webchat'),
    path('salas/amistad/', salas_amistad, name='amistad'),
    path('salas/ligar/', salas_ligar, name='ligar'),
    path('salas/mas-de-40/', salas_masde40, name='masde40'),
    path('salas/amor/', salas_amor, name='amor'),
    path('salas/paises/españa/', paises_españa, name='españa'),
    path('salas/paises/latinoamerica/', paises_latinoamerica, name='latinoamerica'),
    path('salas/relaciones/', salas_ocio, name='relaciones'),
    path('salas/paises/paraguay/', paises_paraguay, name='paraguay'),
    path('salas/paises/argentina/', paises_argentina, name='argentina'),
    path('salas/dev/', salas_dev, name='dev'),
]

main/models.py
from django.db import models
from django.utils import timezone

class HomeCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='home_category_images/')
    link = models.CharField(max_length=200)  # Now just a relative path
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class RecommendedChatRoom(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='recommended_chat_rooms/')
    link = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class ChatRoom(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='chatrooms/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategories/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class ChatRoomLatam(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='chatroomslatam/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategoryLatam(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategorieslatam/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class ChatRoomOcio(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='chatroomsocio/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategoryOcio(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategoriesocio/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategoryParaguay(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategoriesparaguay/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategoryArgentina(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategoriesargentina/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class SubCategoryDev(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='subcategoriesdev/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

class ChatRoomDev(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='chatroomdev/')
    url = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)  # Add this line
    #popularity = models.IntegerField(default=0)  # New field to track popularity

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from blog.models import Post
from .models import *
from django.template.loader import render_to_string
from django.http import HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django_ratelimit.decorators import ratelimit


def get_domain_specific_context(request):
    """
    Helper function to get domain-specific context.
    """
    domain = request.get_host()
    
    # Default values
    title = "Chat Gratis - español"
    chat_branding = "Chat Gratis"
    google_tag_manager_id = ""
    image_url = "images/chat.png"
    canonical_url = request.build_absolute_uri()

    # Domain-specific settings
    if domain == 'web.chateagratis.chat':
        title = "Bienvenidos a ChateaGratis"
        chat_branding = "ChateaGratis"
        google_tag_manager_id = "GTM-XXXXXXX1"
        canonical_url = f"https://web.chateagratis.chat{request.path}"
    elif domain == 'www.chateagratis.chat':
        title = "Bienvenidos a ChateaGratis - Chat Gratis en español"
        chat_branding = "ChateaGratis"
        google_tag_manager_id = "GTM-XXXXXXX2"
        canonical_url = f"https://www.chateagratis.chat{request.path}"
    elif domain == 'chateagratis.chat':
        title = "Bienvenidos a ChateaGratis - Chat Gratis en español"
        chat_branding = "Chatea Gratis"
        google_tag_manager_id = "GTM-PJ8GHV58"
        canonical_url = f"https://chateagratis.chat{request.path}"
    elif domain == 'www.vicio.chat':
        title = "ViciChat - Tu punto de encuentro en español"
        chat_branding = "ViCio.Chat"
        google_tag_manager_id = "GTM-XXXXXXX4"
        canonical_url = f"https://www.vicio.chat{request.path}"
    elif domain == 'vicio.chat':
        title = "ViCio.Chat - Tu punto de encuentro en la red"
        chat_branding = "ViCio.Chat"
        google_tag_manager_id = "GTM-XXXXXXX6"
        image_url = "images/vicio.chat.jpg"
        canonical_url = f"https://vicio.chat{request.path}"
    elif domain == 'www.redlatina.chat':
        title = "RedLatina - Chat Gratis"
        chat_branding = "RedLatina"
        google_tag_manager_id = "GTM-XXXXXXX7"
        canonical_url = f"https://www.redlatina.chat{request.path}"
    elif domain == 'web.redlatina.chat':
        title = "RedLatina - Chat Gratis"
        chat_branding = "Red-Latina"
        google_tag_manager_id = "GTM-XXXXXXX8"
        canonical_url = f"https://web.redlatina.chat{request.path}"
    elif domain == 'redlatina.chat':
        title = "RedLatina - Chat Gratis"
        chat_branding = "RedLatina"
        google_tag_manager_id = "GTM-XXXXXXX9"
        canonical_url = f"https://redlatina.chat{request.path}"

    return {
        'title': title,
        'chat_branding': chat_branding,
        'google_tag_manager_id': google_tag_manager_id,
        'canonical_url': canonical_url,
        'image_url': image_url
    }

def get_meta_information(context_type, chat_branding):
    """
    Helper function to get meta information based on the context type and dynamically insert chat branding.
    """
    meta_info = {
        'meta_title': f"Chat Gratis - español",
        'meta_description': f"Únete a {chat_branding}, la mejor plataforma de chat gratis en español donde puedes conocer gente nueva, hacer amigos y disfrutar de conversaciones en tiempo real.",
        'meta_keywords': "chat gratis, chat en español, conocer gente, amigos, chat online",
        'meta_author': "ChateaGratis",
        'meta_image': "/static/images/chateagratis.chat.svg",
    }

    if context_type == "españa":
        meta_info.update({
            'meta_title': "Chat de España - Chats de España sin registro",
            'meta_description': f"Únete al chat de España en {chat_branding}, la mejor plataforma para conocer gente, hacer amigos y disfrutar de conversaciones en tiempo real en España.",
            'meta_keywords': "chat gratis, chat de españa, chat español, amigos españa, chatear en españa, chicas madrid, chat madrid, chat en español españa",
            'meta_author': "ChateaGratis España",
            'meta_image': "/static/images/chateagratis.chat.svg",
        })
    elif context_type == "latinoamerica":
        meta_info.update({
            'meta_title': "Chats de Latinoamérica para latinos de Latinchat",
            'meta_description': f"Únete al chat de Latinoamérica en {chat_branding}, la mejor plataforma para conocer gente, hacer amigos y disfrutar de conversaciones en tiempo real en Latinoamérica.",
            'meta_keywords': "chat gratis, chat de latinoamérica, chat latino, amigos latinoamérica, chatear en latinoamérica, chicas latinoamérica, chat en español latinoamérica",
            'meta_author': "ChateaGratis Latinoamérica",
            'meta_image': "/media/home_category_images/latinoamerica-1.jpg",
        })
    elif context_type == "paraguay":
        meta_info.update({
            'meta_title': "Chat de Paraguay - Yaguachat - Chat paraguayo",
            'meta_description': f"Únete al chat de Paraguay en {chat_branding}, la mejor plataforma para conocer gente, hacer amigos y disfrutar de conversaciones en tiempo real en Paraguay.",
            'meta_keywords': "chat gratis, chat de paraguay, chat paraguayo, amigos paraguay, chatear en paraguay, chicas asuncion, chat asuncion, chat en español paraguay",
            'meta_author': "Paraguay de Paraguay",
            'meta_image': "/media/chatroomslatam/Paraguay.jpg",
        })
    elif context_type == "argentina":
        meta_info.update({
            'meta_title': "Chats del pais de Argentina - Argentinos y Argentinas chat gratis",
            'meta_description': f"Únete al chat de Argentina en {chat_branding}, la mejor plataforma para conocer gente, hacer amigos y disfrutar de conversaciones en tiempo real en Argentina.",
            'meta_keywords': "chat gratis, chat de argentina, chat argentino, amigos argentina, chatear en argentina, chicas buenos aires, chat buenos aires, chat en español argentina",
            'meta_author': "ChateaGratis Argentina",
            'meta_image': "/media/chatroomslatam/Arg.jpg",
        })
    elif context_type == "home":
        meta_info.update({
            'meta_title': f"{chat_branding} - Chats gratis en español",
            'meta_description': f"Únete a {chat_branding}, la mejor plataforma para conocer gente, hacer amigos y disfrutar de conversaciones en tiempo real.",
            'meta_keywords': "chat gratis, chat de argentina, chat argentino, amigos argentina, chatear en argentina, chicas buenos aires, chat buenos aires, chat en español argentina",
            'meta_author': "ChateaGratis",
            'meta_image': "/static/images/chateagratis.chat.svg",
        })
    
    return meta_info

import random
import requests

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def home(request):
    latest_posts = Post.objects.filter(status=True).order_by('-published_date')[:4]
    home_categories = HomeCategory.objects.all()
    recommended_chat_rooms = RecommendedChatRoom.objects.all()

    # Get domain-specific context
    context = get_domain_specific_context(request)

    # Get news articles from API
    news_url = f"https://api.currentsapi.services/v1/latest-news?language=es&apiKey=_yoXuUAc50lyd-oydhdaH_PyUowjpliAWQ6u2PWkfDPZJEJ4"
    response = requests.get(news_url)
    news_data = response.json().get('news', [])
    
    # Randomize news articles
    if news_data:
        random.shuffle(news_data)
        news_articles = news_data[:4]  # Limit to 4 articles for display
    else:
        news_articles = []

    # Add data to context
    context.update({
        'latest_posts': latest_posts,
        'home_categories': home_categories,
        'recommended_chat_rooms': recommended_chat_rooms,
        'news_articles': news_articles,
        'canonical_url': request.build_absolute_uri(),
    })

    return render(request, 'main/home.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def opciones(request):
    context = get_domain_specific_context(request)
    if request.method == "POST":
        nick = request.POST.get('nick', '')
        join = request.POST.get('join', '')
        show_password = request.POST.get('show_password', '')
        show_password = 'true' if show_password else 'false'
        context.update({'nick': nick, 'join': join, 'show_password': show_password})
    
    return render(request, 'main/opciones.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def webchat(request):
    context = get_domain_specific_context(request)
    if request.method == "POST":
        nick = request.POST.get('nick', '')
        join = request.POST.get('join', '')
        show_password = request.POST.get('show_password', '')
        show_password = 'true' if show_password else 'false'
        context.update({'nick': nick, 'join': join, 'show_password': show_password})
    
    return render(request, 'main/webchat.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def salas_amistad(request):
    context = get_domain_specific_context(request)
    return render(request, 'main/salas/amistad.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def salas_ligar(request):
    context = get_domain_specific_context(request)
    return render(request, 'main/salas/ligar.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def salas_masde40(request):
    context = get_domain_specific_context(request)
    return render(request, 'main/salas/mas-de-40.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt
def salas_amor(request):
    context = get_domain_specific_context(request)
    return render(request, 'main/salas/amor.html', context)

@ratelimit(key='ip', rate='5/m', method='ALL', block=True)
@csrf_exempt

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Dynamic Meta Tags -->
<title>{{ meta_title|default:"ChateaGratis - Chat en español" }}</title>
<meta name="description" content="{{ meta_description|default:'Únete a ChateaGratis, la mejor plataforma de chat gratis en español donde puedes conocer gente nueva, hacer amigos y disfrutar de conversaciones en tiempo real.' }}">
<meta name="keywords" content="{{ meta_keywords|default:'chat gratis, chat en español, conocer gente, amigos, chat online' }}">
<meta name="author" content="{{ meta_author|default:'ChateaGratis' }}">

<!-- Canonical URL -->
<link rel="canonical" href="{{ canonical_url }}">

<!-- Open Graph Meta Tags for Social Media -->
<meta property="og:title" content="{{ meta_title|default:'ChateaGratis - Chat en español' }}">
<meta property="og:description" content="{{ meta_description|default:'Únete a ChateaGratis, la mejor plataforma de chat gratis en español donde puedes conocer gente nueva, hacer amigos y disfrutar de conversaciones en tiempo real.' }}">
<meta property="og:image" content="{{ meta_image|default:'/media/blog_images/852a4d6c-d603-4724-9b5b-e3c5ccf181ba.webp' }}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<meta property="og:type" content="website">

<!-- Twitter Card Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ meta_title|default:'ChateaGratis - Chat en español' }}">
<meta name="twitter:description" content="{{ meta_description|default:'Únete a ChateaGratis, la mejor plataforma de chat gratis en español donde puedes conocer gente nueva, hacer amigos y disfrutar de conversaciones en tiempo real.' }}">
<meta name="twitter:image" content="{{ meta_image|default:'/static/images/chateagratis.chat.svg' }}">


<link rel="icon" href="{% static 'images/favicon.ico' %}" sizes="32x32">
<link rel="apple-touch-icon" href="{% static 'images/favicon.ico' %}">
<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" type="text/css" media="all">

    

    <!-- Google Tag Manager -->
    {% if google_tag_manager_id %}
    <script>
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','{{ google_tag_manager_id }}');
    </script>
    <!-- End Google Tag Manager -->
    {% endif %}
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-QNMRBVJLWP"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-QNMRBVJLWP');
    </script>
</head>
<body>
    <div class="site" id="page">
        {% include 'main/navbar.html' %}
        
            {% block content %}
            <!-- Page specific content will go here -->
            {% endblock %}

            {% include 'main/cookie_consent.html' %}
        {% include 'main/footer.html' %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- jQuery, Popper.js, and Bootstrap JS (for navbar toggling) -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

main/templates/main/footer.html
{% load static %}
<div class="container-fluid" style="background:#F3F3F3;">
    <div class="container py-4">
        <div class="row mt-4">
            <div class="col-12">
                <div>
                    <p><b>{{ chat_branding }}</b> es tu comunidad de chat en español completamente gratis, formada por usuarios de toda España, México, Argentina, Chile y toda Latinoamérica que buscan nuevos amigos.</p>
                    <p><b>Chatea</b>, conoce gente, liga y haz nuevos amigos y muchos de los servicios que te ofrecemos (registrar un apodo, crear tu propia sala de chat, etc.) son completamente gratuitos.</p>
                    <p>Nuestro <b>webchat</b> en constante evolución le permitirá chatear libremente sin registrarse de una manera sencilla y clara. Con solo registrarte, puedes cargar tus fotos y videos favoritos y crear una página completamente personalizada sobre ti y tu comunidad.</p>
                    <p>En definitiva, <b>{{ chat_branding }}</b> te ofrece un <b>chat gratis</b> para ti y tus amigos, para que puedas chatear fácilmente desde nuestra web o llevar este chat a tu chat. Los amigos para chatear online son los que más se han desarrollado en los últimos años, con el mejor ambiente y la mejor gente.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="wrapper" id="wrapper-footer-full">
    <div class="container" id="footer-full-content" tabindex="-1">
        <div class="row">
            <div class="col-sm-3 d-lg-block d-sm-block d-none">
                <h5>Top canales</h5>
                <ul class="fa-ul">
                    {% for top_channel in top_channels %}
                    <li><span class="fa-li"><i class="fab fa-slack-hash"></i></span><a href="{{ top_channel.url }}">{{ top_channel.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-3 d-lg-block d-sm-block d-none">
                <h5>Últimos canales</h5>
                <ul class="fa-ul">
                    {% for recent_channel in recent_channels %}
                    <li><span class="fa-li"><i class="fab fa-slack-hash"></i></span><a href="{{ recent_channel.url }}">{{ recent_channel.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-3 d-lg-block d-sm-block d-none">
                <h5>Corporativo</h5>
                <ul class="fa-ul">
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/historia/">Historia</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/equipo/">Equipo</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/auth/register/">Registro</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/crea-tu-chat/">Crea tu chat</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/contacto/">Contacto</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h5>Legal</h5>
                <ul class="fa-ul">
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/legal/aviso-legal/">Aviso legal</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/legal/politica-de-privacidad/">Política de privacidad</a></li>
                    <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="/politica-de-cookies/">Política de cookies</a></li>
                </ul>
            </div>
        </div>
        <div class="col-12 my-4 text-center">
            <div class="fa-stack"><a href="#" target="_blank" aria-label="lee esto en facebook"><i class="fas fa-circle fa-stack-2x"></i><i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i></a></div>
            <div class="fa-stack"><a href="#" target="_blank" aria-label="lee esto en twitter"><i class="fas fa-circle fa-stack-2x"></i><i class="fab fa-twitter fa-stack-1x fa-inverse"></i></a></div>
        </div>
        <div class="col-12 text-center">© 2022-2024 | {{ chat_branding }} Networks</div>
    </div>
</div>

main/templates/main/navbar.html
{% load static %}
<div id="wrapper-navbar">
    <a class="skip-link sr-only sr-only-focusable" href="#content">Saltar al contenido</a>
    <nav class="navbar navbar-expand-md navbar-light bg-vc-dark">
        <div class="container">
            <a href="{% url 'home' %}" class="navbar-brand">
                <img width="100" height="100" src="{% static 'images/chateagratis.chat.svg' %}" class="img-fluid" alt="Chat gratis">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarNavDropdown" class="collapse navbar-collapse">
                <ul id="main-menu" class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-folder-open"></i> España</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-folder-open"></i> Latinos</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-folder-open"></i> Ocio</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-folder-open"></i> Relaciones</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-balance-scale"></i> Horoscopo</a></li>
                    <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link"><i class="fas fa-newspaper"></i> Blog</a></li>
                    <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-question-circle"></i> Ayuda</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>

main/templates/main/opciones.html
{% extends "main/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Opciones</h2>
    <form method="post" action="{% url 'opciones' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="nick">Nickname</label>
            <input type="text" class="form-control" id="nick" name="nick" value="{{ nick }}" required>
        </div>

        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" value="true" id="show_password" name="show_password" {% if show_password == 'true' %}checked{% endif %}>
            <label class="form-check-label" for="show_password">
                Tengo contraseña
            </label>
        </div>

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

    <hr>

    <h3 class="text-center">Opciones Guardadas</h3>
    <p><strong>Nickname:</strong> {{ nick }}</p>
    <p><strong>Mostrar contraseña:</strong> {{ show_password|yesno:"Sí,No" }}</p>
</div>
{% endblock %}